/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aida.frame;

import java.awt.Color;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Maicol Andres
 */
public class Register extends javax.swing.JFrame {
    public static LinkedList modelo=new LinkedList();
    private User lista3[]=new User[4];
    int posicion=0,n2=0;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtnombres = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtidentificacion = new javax.swing.JTextField();
        txtcelular = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        txtpin = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtfechaN = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        txtcontrasena = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        txtnumeroCuenta = new javax.swing.JTextField();
        btnVer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnombres.setBackground(new java.awt.Color(0, 51, 204));
        txtnombres.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtnombres.setForeground(new java.awt.Color(255, 255, 255));
        txtnombres.setText("Nombres Completos");
        txtnombres.setBorder(null);
        txtnombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnombresMousePressed(evt);
            }
        });
        jPanel2.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        txtcorreo.setBackground(new java.awt.Color(0, 51, 204));
        txtcorreo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtcorreo.setText("Correo electronico");
        txtcorreo.setBorder(null);
        txtcorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcorreoMousePressed(evt);
            }
        });
        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });
        jPanel2.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        txtidentificacion.setBackground(new java.awt.Color(0, 51, 204));
        txtidentificacion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtidentificacion.setForeground(new java.awt.Color(255, 255, 255));
        txtidentificacion.setText("Cédula");
        txtidentificacion.setBorder(null);
        txtidentificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtidentificacionMousePressed(evt);
            }
        });
        jPanel2.add(txtidentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        txtcelular.setBackground(new java.awt.Color(0, 51, 204));
        txtcelular.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtcelular.setForeground(new java.awt.Color(255, 255, 255));
        txtcelular.setText("Numero de telefono");
        txtcelular.setBorder(null);
        txtcelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcelularMousePressed(evt);
            }
        });
        jPanel2.add(txtcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 123, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 123, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 123, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 140, 10));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ver");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 196, 15)));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 80, 40));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ingresar");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 196, 15)));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 80, 40));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("REGISTRO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 200, 30));

        jTextField1.setBackground(new java.awt.Color(111, 156, 198));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 70));

        btnIngresar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(240, 240, 240));
        btnIngresar.setBorder(null);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 80, 40));

        txtpin.setBackground(new java.awt.Color(0, 51, 204));
        txtpin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtpin.setForeground(new java.awt.Color(255, 255, 255));
        txtpin.setText("PIN");
        txtpin.setBorder(null);
        txtpin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpinMousePressed(evt);
            }
        });
        txtpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpinActionPerformed(evt);
            }
        });
        jPanel2.add(txtpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 100, 10));

        txtfechaN.setBackground(new java.awt.Color(0, 51, 204));
        txtfechaN.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtfechaN.setForeground(new java.awt.Color(255, 255, 255));
        txtfechaN.setText("Fecha de Nacimiento");
        txtfechaN.setBorder(null);
        txtfechaN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtfechaNMousePressed(evt);
            }
        });
        jPanel2.add(txtfechaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 123, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 123, 10));

        txtcontrasena.setBackground(new java.awt.Color(0, 51, 204));
        txtcontrasena.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtcontrasena.setForeground(new java.awt.Color(255, 255, 255));
        txtcontrasena.setText("Contraseña");
        txtcontrasena.setBorder(null);
        txtcontrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcontrasenaMousePressed(evt);
            }
        });
        jPanel2.add(txtcontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 123, 10));

        txtnumeroCuenta.setBackground(new java.awt.Color(0, 51, 204));
        txtnumeroCuenta.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtnumeroCuenta.setForeground(new java.awt.Color(255, 255, 255));
        txtnumeroCuenta.setText("Número de Cuenta");
        txtnumeroCuenta.setBorder(null);
        txtnumeroCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnumeroCuentaMousePressed(evt);
            }
        });
        jPanel2.add(txtnumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        jPanel2.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 80, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9088655f-57d7-4c8d-b04c-343e846c196a.jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumeroCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnumeroCuentaMousePressed
        // TODO add your handling code here:
        if(String.valueOf(txtnumeroCuenta.getText()).equalsIgnoreCase("Número de Cuenta")){
            txtnumeroCuenta.setText("");
            txtnumeroCuenta.setForeground(Color.black);
        }
        if(String.valueOf(txtcontrasena.getText()).isEmpty()){
            txtcontrasena.setText("Contraseña");
            txtcontrasena.setForeground(Color.black);
        }
        if(txtfechaN.getText().isEmpty()){
            txtfechaN.setText("Fecha de Nacimiento");
            txtfechaN.setForeground(Color.black);
        }
        if(String.valueOf(txtpin.getText()).isEmpty()){
            txtpin.setText("PIN");
            txtpin.setForeground(Color.black);
        }
        if(String.valueOf(txtcelular.getText()).isEmpty()){
            txtcelular.setText("Numero de telefono");
            txtcelular.setForeground(Color.black);
        }
        if(txtidentificacion.getText().isEmpty()){
            txtidentificacion.setText("Cédula");
            txtidentificacion.setForeground(Color.black);
        }
        if(String.valueOf(txtcorreo.getText()).isEmpty()){
            txtcorreo.setText("Correo electronico");
            txtcorreo.setForeground(Color.black);
        }
        if(String.valueOf(txtnombres.getText()).isEmpty()){
            txtnombres.setText("Nombres Completos");
            txtnombres.setForeground(Color.black);
        }

    }//GEN-LAST:event_txtnumeroCuentaMousePressed

    private void txtcontrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcontrasenaMousePressed
        // TODO add your handling code here:
        if(String.valueOf(txtcontrasena.getText()).equalsIgnoreCase("Contraseña")){
            txtcontrasena.setText("");
            txtcontrasena.setForeground(Color.black);
        }
        if(txtfechaN.getText().isEmpty()){
            txtfechaN.setText("Fecha de Nacimiento");
            txtfechaN.setForeground(Color.black);
        }
        if(String.valueOf(txtpin.getText()).isEmpty()){
            txtpin.setText("PIN");
            txtpin.setForeground(Color.black);
        }
        if(String.valueOf(txtcelular.getText()).isEmpty()){
            txtcelular.setText("Numero de telefono");
            txtcelular.setForeground(Color.black);
        }
        if(txtidentificacion.getText().isEmpty()){
            txtidentificacion.setText("Cédula");
            txtidentificacion.setForeground(Color.black);
        }
        if(String.valueOf(txtcorreo.getText()).isEmpty()){
            txtcorreo.setText("Correo electronico");
            txtcorreo.setForeground(Color.black);
        }
        if(String.valueOf(txtnombres.getText()).isEmpty()){
            txtnombres.setText("Nombres Completos");
            txtnombres.setForeground(Color.black);
        }
        if(String.valueOf(txtnumeroCuenta.getText()).isEmpty()){
            txtnumeroCuenta.setText("Número de Cuenta");
            txtnumeroCuenta.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtcontrasenaMousePressed

    private void txtfechaNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfechaNMousePressed
        // TODO add your handling code here:
        if(txtfechaN.getText().equals("Fecha de Nacimiento")){
            txtfechaN.setText("");
            txtfechaN.setForeground(Color.black);
        }
        if(String.valueOf(txtpin.getText()).isEmpty()){
            txtpin.setText("PIN");
            txtpin.setForeground(Color.black);
        }
        if(String.valueOf(txtcelular.getText()).isEmpty()){
            txtcelular.setText("Numero de telefono");
            txtcelular.setForeground(Color.black);
        }
        if(txtidentificacion.getText().isEmpty()){
            txtidentificacion.setText("Cédula");
            txtidentificacion.setForeground(Color.black);
        }
        if(String.valueOf(txtcorreo.getText()).isEmpty()){
            txtcorreo.setText("Correo electronico");
            txtcorreo.setForeground(Color.black);
        }
        if(String.valueOf(txtnombres.getText()).isEmpty()){
            txtnombres.setText("Nombres Completos");
            txtnombres.setForeground(Color.black);
        }

        if(String.valueOf(txtcontrasena.getText()).isEmpty()){
            txtcontrasena.setText("Contraseña");
            txtcontrasena.setForeground(Color.black);
        }
        if(String.valueOf(txtnumeroCuenta.getText()).isEmpty()){
            txtnumeroCuenta.setText("Número de Cuenta");
            txtnumeroCuenta.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtfechaNMousePressed

    private void txtpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpinActionPerformed

    private void txtpinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpinMousePressed
        // TODO add your handling code here:
        if(String.valueOf(txtpin.getText()).equalsIgnoreCase("PIN")){
            txtpin.setText("");
            txtpin.setForeground(Color.black);
        }
        if(String.valueOf(txtcelular.getText()).isEmpty()){
            txtcelular.setText("Numero de telefono");
            txtcelular.setForeground(Color.black);
        }
        if(txtidentificacion.getText().isEmpty()){
            txtidentificacion.setText("Cédula");
            txtidentificacion.setForeground(Color.black);
        }
        if(String.valueOf(txtcorreo.getText()).isEmpty()){
            txtcorreo.setText("Correo electronico");
            txtcorreo.setForeground(Color.black);
        }
        if(String.valueOf(txtnombres.getText()).isEmpty()){
            txtnombres.setText("Nombres Completos");
            txtnombres.setForeground(Color.black);
        }

        if(txtfechaN.getText().isEmpty()){
            txtfechaN.setText("Fecha de Nacimiento");
            txtfechaN.setForeground(Color.black);
        }
        if(String.valueOf(txtcontrasena.getText()).isEmpty()){
            txtcontrasena.setText("Contraseña");
            txtcontrasena.setForeground(Color.black);
        }
        if(String.valueOf(txtnumeroCuenta.getText()).isEmpty()){
            txtnumeroCuenta.setText("Número de Cuenta");
            txtnumeroCuenta.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtpinMousePressed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        try{
            String nombre,identificacion, nCuenta,pin,contrasena;
            nombre=txtnombres.getText();
            identificacion=txtidentificacion.getText();
            nCuenta=txtnumeroCuenta.getText();
            pin=txtpin.getText();
            contrasena=txtcontrasena.getText();
            User a1=new User(nombre,identificacion,nCuenta,pin,contrasena);
            modelo.add(a1);
            JOptionPane.showMessageDialog(null, "Gracias por Registrarse!");
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtcelularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcelularMousePressed
        // TODO add your handling code here:
        if(String.valueOf(txtcelular.getText()).equalsIgnoreCase("Numero de telefono")){
            txtcelular.setText("");
            txtcelular.setForeground(Color.black);
        }
        if(txtidentificacion.getText().isEmpty()){
            txtidentificacion.setText("Cédula");
            txtidentificacion.setForeground(Color.black);
        }
        if(String.valueOf(txtcorreo.getText()).isEmpty()){
            txtcorreo.setText("Correo electronico");
            txtcorreo.setForeground(Color.black);
        }
        if(String.valueOf(txtnombres.getText()).isEmpty()){
            txtnombres.setText("Nombres Completos");
            txtnombres.setForeground(Color.black);
        }
        if(String.valueOf(txtpin.getText()).isEmpty()){
            txtpin.setText("PIN");
            txtpin.setForeground(Color.black);
        }
        if(txtfechaN.getText().isEmpty()){
            txtfechaN.setText("Fecha de Nacimiento");
            txtfechaN.setForeground(Color.black);
        }
        if(String.valueOf(txtcontrasena.getText()).isEmpty()){
            txtcontrasena.setText("Contraseña");
            txtcontrasena.setForeground(Color.black);
        }
        if(String.valueOf(txtnumeroCuenta.getText()).isEmpty()){
            txtnumeroCuenta.setText("Número de Cuenta");
            txtnumeroCuenta.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtcelularMousePressed

    private void txtidentificacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidentificacionMousePressed
        // TODO add your handling code here:
        if(txtidentificacion.getText().equals("Cédula")){
            txtidentificacion.setText("");
            txtidentificacion.setForeground(Color.black);
        }
        if(String.valueOf(txtcorreo.getText()).isEmpty()){
            txtcorreo.setText("Correo electronico");
            txtcorreo.setForeground(Color.black);
        }
        if(String.valueOf(txtnombres.getText()).isEmpty()){
            txtnombres.setText("Nombres Completos");
            txtnombres.setForeground(Color.black);
        }

        if(String.valueOf(txtcelular.getText()).isEmpty()){
            txtcelular.setText("Numero de telefono");
            txtcelular.setForeground(Color.black);
        }
        if(String.valueOf(txtpin.getText()).isEmpty()){
            txtpin.setText("PIN");
            txtpin.setForeground(Color.black);
        }
        if(txtfechaN.getText().isEmpty()){
            txtfechaN.setText("Fecha de Nacimiento");
            txtfechaN.setForeground(Color.black);
        }
        if(String.valueOf(txtcontrasena.getText()).isEmpty()){
            txtcontrasena.setText("Contraseña");
            txtcontrasena.setForeground(Color.black);
        }
        if(String.valueOf(txtnumeroCuenta.getText()).isEmpty()){
            txtnumeroCuenta.setText("Número de Cuenta");
            txtnumeroCuenta.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtidentificacionMousePressed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void txtcorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcorreoMousePressed
        // TODO add your handling code here:
        if(String.valueOf(txtcorreo.getText()).equals("Correo electronico")){
            txtcorreo.setText("");
            txtcorreo.setForeground(Color.black);
        }
        if(String.valueOf(txtnombres.getText()).isEmpty()){
            txtnombres.setText("Nombres Completos");
            txtnombres.setForeground(Color.black);
        }

        if(txtidentificacion.getText().isEmpty()){
            txtidentificacion.setText("Cédula");
            txtidentificacion.setForeground(Color.black);
        }
        if(String.valueOf(txtcelular.getText()).isEmpty()){
            txtcelular.setText("Numero de telefono");
            txtcelular.setForeground(Color.black);
        }
        if(String.valueOf(txtpin.getText()).isEmpty()){
            txtpin.setText("PIN");
            txtpin.setForeground(Color.black);
        }
        if(txtfechaN.getText().isEmpty()){
            txtfechaN.setText("Fecha de Nacimiento");
            txtfechaN.setForeground(Color.black);
        }
        if(String.valueOf(txtcontrasena.getText()).isEmpty()){
            txtcontrasena.setText("Contraseña");
            txtcontrasena.setForeground(Color.black);
        }
        if(String.valueOf(txtnumeroCuenta.getText()).isEmpty()){
            txtnumeroCuenta.setText("Número de Cuenta");
            txtnumeroCuenta.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtcorreoMousePressed

    private void txtnombresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombresMousePressed
        // TODO add your handling code here:
        if(String.valueOf(txtnombres.getText()).equals("Nombres Completos")){
            txtnombres.setText("");
            txtnombres.setForeground(Color.black);
        }
        if(String.valueOf(txtcorreo.getText()).isEmpty()){
            txtcorreo.setText("Correo electronico");
            txtcorreo.setForeground(Color.black);
        }
        if(txtidentificacion.getText().isEmpty()){
            txtidentificacion.setText("Cédula");
            txtidentificacion.setForeground(Color.black);
        }
        if(String.valueOf(txtcelular.getText()).equals("Ingrese monto a pagar $")){
            txtcelular.setText("Numero de telefono");
            txtcelular.setForeground(Color.black);
        }
        if(String.valueOf(txtpin.getText()).isEmpty()){
            txtpin.setText("PIN");
            txtpin.setForeground(Color.black);
        }
        if(txtfechaN.getText().isEmpty()){
            txtfechaN.setText("Fecha de Nacimiento");
            txtfechaN.setForeground(Color.black);
        }
        if(String.valueOf(txtcontrasena.getText()).equals("Ingrese monto a pagar $")){
            txtcontrasena.setText("Contraseña");
            txtcontrasena.setForeground(Color.black);
        }
        if(String.valueOf(txtnumeroCuenta.getText()).isEmpty()){
            txtnumeroCuenta.setText("Número de Cuenta");
            txtnumeroCuenta.setForeground(Color.black);
        }

    }//GEN-LAST:event_txtnombresMousePressed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
         Administrator q = new Administrator();
            this.setVisible(false);
            q.setVisible(true);
    }//GEN-LAST:event_btnVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField txtcelular;
    public javax.swing.JTextField txtcontrasena;
    public javax.swing.JTextField txtcorreo;
    public javax.swing.JTextField txtfechaN;
    public javax.swing.JTextField txtidentificacion;
    public javax.swing.JTextField txtnombres;
    public javax.swing.JTextField txtnumeroCuenta;
    public javax.swing.JTextField txtpin;
    // End of variables declaration//GEN-END:variables
}
